<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net6.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <RootNamespace>SpecIFicator.Apps.BlazorWPF</RootNamespace>
        <ApplicationIcon>SpecIFicator.ico</ApplicationIcon>
        <AssemblyName>SpecIFicator</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="SpecIFicator.ico" />
    </ItemGroup>


    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Components" Version="6.0.25" />
      <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Wpf" Version="6.0.547" />
      <PackageReference Include="Microsoft.AspNetCore.Localization" Version="2.2.0" />
      <PackageReference Include="NLog" Version="4.5.11" />
    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\..\..\MDD4All.FileAccess.WPF\src\MDD4All.FileAccess.WPF\MDD4All.FileAccess.WPF-dev.csproj" />
      <ProjectReference Include="..\..\..\SpecIFicator.Framework\src\SpecIFicator.Framework\SpecIFicator.Framework-dev.csproj" />
      <ProjectReference Include="..\..\..\SplitJs.Blazor\src\SplitJs.Blazor\SplitJs.Blazor-dev.csproj" />      
      <ProjectReference Include="..\..\..\Summernote\src\BlazingComponents.Summernote\BlazingComponents.Summernote-dev.csproj" />
      <ProjectReference Include="..\..\..\VisNetwork.Blazor\src\VisNetwork.Blazor\VisNetwork.Blazor-dev.csproj" />
    </ItemGroup>


    <ItemGroup>
      <Content Update="wwwroot\images\IconError.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Update="wwwroot\images\IconFail.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Update="wwwroot\images\IconInconclusive.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Update="wwwroot\images\IconNotTested.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Update="wwwroot\images\IconPass.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
